package publish

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

var (
	pubOutput string
	pubTitle  string
	pubTheme  string
)

func findMarkdownFiles(dir string) []string {
	var files []string
	filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil { return nil }
		if info.IsDir() {
			n := info.Name()
			if strings.HasPrefix(n, ".") || n == "node_modules" { return filepath.SkipDir }
			return nil
		}
		if strings.HasSuffix(info.Name(), ".md") { files = append(files, path) }
		return nil
	})
	return files
}

func simpleMarkdownToHTML(md string) string {
	var b strings.Builder
	lines := strings.Split(md, "\n")
	inCode := false
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		if strings.HasPrefix(line, "```") {
			if inCode { b.WriteString("</code></pre>\n") } else { b.WriteString("<pre><code>") }
			inCode = !inCode
			continue
		}
		if inCode { b.WriteString(line + "\n"); continue }
		if strings.HasPrefix(line, "### ") { b.WriteString("<h3>" + line[4:] + "</h3>\n"); continue }
		if strings.HasPrefix(line, "## ") { b.WriteString("<h2>" + line[3:] + "</h2>\n"); continue }
		if strings.HasPrefix(line, "# ") { b.WriteString("<h1>" + line[2:] + "</h1>\n"); continue }
		if strings.HasPrefix(line, "- ") {
			c := strings.TrimPrefix(line, "- ")
			if strings.HasPrefix(c, "[ ] ") { b.WriteString("<li><input type=checkbox>" + c[4:] + "</li>\n") } else if strings.HasPrefix(c, "[x] ") { b.WriteString("<li><input type=checkbox checked>" + c[4:] + "</li>\n") } else { b.WriteString("<li>" + c + "</li>\n") }
			continue
		}
		if strings.HasPrefix(line, "> ") { b.WriteString("<blockquote>" + line[2:] + "</blockquote>\n"); continue }
		if strings.TrimSpace(line) == "" { b.WriteString("<br>\n"); continue }
		b.WriteString("<p>" + line + "</p>\n")
	}
	return b.String()
}

func generateSite(root, output string) error {
	os.MkdirAll(output, 0755)
	files := findMarkdownFiles(root)
	if len(files) == 0 {
		return fmt.Errorf("no markdown files found in %s", root)
	}

	name := pubTitle
	if name == "" {
		name = filepath.Base(root)
	}

	// Generate each page
	pages := []map[string]string{}
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil { continue }
		content := string(data)
		rel, _ := filepath.Rel(root, file)

		var fm map[string]string
		body := content
		if strings.HasPrefix(content, "---\n") {
			end := strings.Index(content[4:], "\n---\n")
			if end > 0 {
				fm = parseFrontmatter(content[4 : 4+end])
				body = content[4+end+5:]
			}
		}

		title := strings.TrimSuffix(filepath.Base(rel), ".md")
		if fm != nil && fm["title"] != "" {
			title = fm["title"]
		}

		outFile := filepath.Join(output, strings.TrimSuffix(rel, ".md")+".html")
		os.MkdirAll(filepath.Dir(outFile), 0755)

		html := simpleMarkdownToHTML(body)
		page := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>%s — %s</title>
<style>
  :root { --bg: #fff; --fg: #1a1a1a; --muted: #666; --border: #eee; --link: #2563eb; --code-bg: #f5f5f5; }
  @media (prefers-color-scheme: dark) { :root { --bg: #1a1a2e; --fg: #e0e0e0; --muted: #999; --border: #333; --link: #60a5fa; --code-bg: #2a2a3e; } }
  body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: var(--fg); background: var(--bg); }
  pre { background: var(--code-bg); padding: 1rem; border-radius: 6px; overflow-x: auto; }
  code { background: var(--code-bg); padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
  pre code { background: none; padding: 0; }
  blockquote { border-left: 3px solid var(--border); margin: 0; padding-left: 1rem; color: var(--muted); }
  table { border-collapse: collapse; width: 100%%; }
  th, td { border: 1px solid var(--border); padding: 8px; text-align: left; }
  th { background: var(--code-bg); }
  a { color: var(--link); text-decoration: none; }
  a:hover { text-decoration: underline; }
  nav { margin-bottom: 2rem; padding: 1rem; background: var(--code-bg); border-radius: 6px; }
  nav a { margin-right: 1rem; font-weight: 500; }
  .frontmatter { background: var(--code-bg); padding: 1rem; border-radius: 6px; margin-bottom: 1rem; font-size: 0.9em; }
  .frontmatter dt { font-weight: 600; margin-top: 0.5rem; }
  .frontmatter dd { margin-left: 0; color: var(--muted); }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.85em; text-align: center; }
</style>
</head>
<body>
<nav>
  <a href="/">%s</a>
  <a href="/index.html">Index</a>
</nav>
<article>
<h1>%s</h1>
%s
</article>
<footer>
  <p>Generated by down.nvim — %s</p>
</footer>
</body>
</html>`, title, name, name, title, html, time.Now().Format("2006-01-02"))

		os.WriteFile(outFile, []byte(page), 0644)
		pages = append(pages, map[string]string{"path": rel, "title": title})
	}

	// Generate index page
	indexHTML := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>%s — Index</title>
<style>
  :root { --bg: #fff; --fg: #1a1a1a; --muted: #666; --border: #eee; --link: #2563eb; --code-bg: #f5f5f5; }
  @media (prefers-color-scheme: dark) { :root { --bg: #1a1a2e; --fg: #e0e0e0; --muted: #999; --border: #333; --link: #60a5fa; --code-bg: #2a2a3e; } }
  body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: var(--fg); background: var(--bg); }
  a { color: var(--link); text-decoration: none; }
  a:hover { text-decoration: underline; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1rem; }
  .card { padding: 1rem; border: 1px solid var(--border); border-radius: 6px; }
  .card h3 { margin: 0 0 0.5rem 0; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.85em; text-align: center; }
</style>
</head>
<body>
<h1>%s</h1>
<p>%d notes</p>
<div class="grid">
`, name, name, len(pages))

	for _, p := range pages {
		href := strings.TrimSuffix(p["path"], ".md") + ".html"
		indexHTML += fmt.Sprintf(`<a href="%s"><div class="card"><h3>%s</h3><p style="color:var(--muted);font-size:0.85em">%s</p></div></a>`+"\n", href, p["title"], p["path"])
	}

	indexHTML += fmt.Sprintf(`</div>
<footer><p>Generated by down.nvim — %s</p></footer>
</body>
</html>`, time.Now().Format("2006-01-02"))

	os.WriteFile(filepath.Join(output, "index.html"), []byte(indexHTML), 0644)
	return nil
}

func parseFrontmatter(fm string) map[string]string {
	result := map[string]string{}
	for _, line := range strings.Split(fm, "\n") {
		line = strings.TrimSpace(line)
		if k, v, ok := strings.Cut(line, ":"); ok {
			result[strings.TrimSpace(k)] = strings.TrimSpace(v)
		}
	}
	return result
}

var Publish = cobra.Command{
	Use:     "publish [directory]",
	Aliases: []string{"site"},
	Short:   "Generate static HTML site from workspace",
	Long:    "Generate a static HTML website from a workspace of markdown notes. Creates index page, individual note pages, and supports dark mode.",
	Run: func(cmd *cobra.Command, args []string) {
		root := "."
		if len(args) > 0 { root = args[0] }
		output := pubOutput
		if output == "" {
			output = filepath.Join(root, ".down", "site")
		}
		if err := generateSite(root, output); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("Site generated at %s\nOpen %s/index.html in your browser.\n", output, output)
	},
}

func init() {
	Publish.Flags().StringVarP(&pubOutput, "output", "o", "", "Output directory")
	Publish.Flags().StringVarP(&pubTitle, "title", "t", "", "Site title")
}
